Update command flag detail to quickstart.md
Current documentation under: Build the add on uses  the command:
ucc-gen build --source demo_addon_for_splunk/package 

If copied and pasted from the code block and them executed, this would throw the error: 
ERROR: Could not determine a version using Git (maybe not a Git repository?). Use `--ta-version` to specify the version you want. 

This commit adds the missing `--ta-version` to the code block.