fix: allow packaging from 23.0 (#1484)
**Issue number:** N/A

### PR Type

**What kind of change does this PR introduce?**
* [ ] Feature
* [x] Bug Fix
* [ ] Refactoring (no functional or API changes)
* [ ] Documentation Update
* [ ] Maintenance (dependency updates, CI, etc.)

## Summary

### Changes

Allow `packaging` from a version "23.0".

To reproduce the issue run

```bash
pip install splunk-add-on-ucc-framework==5.53.1
pip install splunk-appinspect==3.8.1
```

You should see

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
splunk-add-on-ucc-framework 5.53.1 requires packaging==24.0, but you have packaging 23.0 which is incompatible.
```

in your console.

### User experience

Developers can install latest version of both UCC and Splunk AppInspect
CLI in the same virtual environment.

## Checklist

If an item doesn't apply to your changes, leave it unchecked.

* [x] I have performed a self-review of this change according to the
[development
guidelines](https://splunk.github.io/addonfactory-ucc-generator/contributing/#development-guidelines)
* [ ] Tests have been added/modified to cover the changes [(testing
doc)](https://splunk.github.io/addonfactory-ucc-generator/contributing/#build-and-test)
* [ ] Changes are documented
* [x] PR title and description follows the [contributing
principles](https://splunk.github.io/addonfactory-ucc-generator/contributing/#pull-requests)